---
apiVersion: v1
kind: Service
metadata:
  name: polyshop-green
  labels:
    app: polymerjs-shop
    environment: green
  namespace: polyshop
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
  selector:
    app: polymerjs-shop
    environment: green
