---
apiVersion: v1
kind: Service
metadata:
  name: polyshop-blue
  labels:
    app: polymerjs-shop
    environment: blue
  namespace: polyshop
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    app: polymerjs-shop
    environment: blue
