---
apiVersion: v1
kind: Service
metadata:
  name: polyshop-prod
  labels:
    app: polymerjs-shop-prod
    environment: production
  namespace: polyshop
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30003
  selector:
    app: polymerjs-shop
    environment: blue
